[package]
# The name that will be displayed in Add/Remove Programs
product_name = "ZLT System Monitor"
# The unique identifier for the product
product_version = "1.0.0"
# Manufacturer is a required field, but can be any value
manufacturer = "ZLT"

[build]
# Path to the WiX source (.wxs) file
input_file = "wix/main.wxs"
# Path where the built MSI will be written
output_path = "installer"
# Path to the compiled release binary
binary_path = "target/release/zlt.exe"
# Path to the license file
license = "wix/license.rtf"

[settings]
# Additional compiler (candle.exe) arguments
# candle_args = []
# Additional linker (light.exe) arguments
# light_args = []

[log]
# Log level (off, error, warn, info, debug, trace)
level = "info"

[cultures]
# Default UI language
default = "en-US"
# Supported UI languages
enabled = ["en-US"]
