name: Build Windows MSI Installer

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc
    
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
    
    - name: Install WiX Toolset
      run: |
        $wixToolsetUrl = "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe"
        Invoke-WebRequest -Uri $wixToolsetUrl -OutFile wix311.exe
        Start-Process -FilePath .\wix311.exe -ArgumentList "/install","/quiet" -NoNewWindow -Wait
        echo "$env:WIX\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
    - name: Install cargo-wix
      run: cargo install cargo-wix
    
    - name: Build Release Binary
      run: cargo build --release
    
    - name: Build MSI Installer
      run: cargo wix
    
    - name: Rename MSI Installer
      run: |
        $msiFile = Get-ChildItem -Path target\wix\*.msi | Select-Object -First 1
        $version = (Get-Date -Format "yyyy.MM.dd.HHmm")
        $newName = "ZLT-System-Monitor-$version.msi"
        Rename-Item -Path $msiFile.FullName -NewName $newName
        echo "MSI_PATH=target\wix\$newName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    
    - name: Upload MSI Artifact
      uses: actions/upload-artifact@v3
      with:
        name: zlt-windows-installer
        path: target\wix\*.msi
        retention-days: 90

    # Create GitHub Release if this is a tag
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.MSI_PATH }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
